<?php

namespace SchoolBundle\Repository;

use SchoolBundle\Entity\User;

/**
 * ClassAssignmentRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class ClassAssignmentRepository extends \Doctrine\ORM\EntityRepository
{

    public function delAssociation($class_id,$user){
         $qb = $this->createQueryBuilder('ca')
         ->delete()
         ->where('class=?1 AND user=?2')
         ->setParameter(1,$class_id)
         ->setParameter(2,$user);    
    }

    public function addAssociation($class_id,$user){
         $qb = $this->createQueryBuilder('ca')
         ->insert('ClassAssignment')
         ->values(array(
             'class' => '?1',
             'user' =>'?2'
         ))
         ->setParameter(1,$class_id)
         ->setParameter(2,$user);    
    }

     
}
