<?php

namespace SchoolBundle\Repository;

/**
 * StudentRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class UserRepository extends \Doctrine\ORM\EntityRepository
{
    public function getNbUsers(){
        $qb = $this->createQueryBuilder('u')
        ->select('COUNT(u) ')
        ->where('u.role=?1')
        ->setParameter('1',"");
        $result = $qb
            ->getQuery()
            ->getSingleScalarResult();
       
        return $result;
    }
}
