<?php

namespace ExerciseBundle\Repository;

/**
 * ExerciseRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class ExerciseRepository extends \Doctrine\ORM\EntityRepository
{
    public function getNbGlobal(){
        $qb = $this->createQueryBuilder('e')
            ->select('COUNT(e)')
            //->where('role=""');
            ;
        $result = $qb
            ->getQuery()
            ->getSingleScalarResult();
        return $result;
    }
}
