<?php

namespace AppBundle\Repository;

/**
 * ClassAssignmentRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class ClassAssignmentRepository extends \Doctrine\ORM\EntityRepository
{
}
