exercice_thumbnail:
    resource: "@ExerciceBundle/Controller/ThumbnailController.php"
    type:     annotation

school:
    resource: "@SchoolBundle/Controller/"
    type:     annotation
    prefix:   /

exercice:
    resource: "@ExerciceBundle/Controller/"
    type:     annotation
    prefix:   /

app:
    resource: "@AppBundle/Controller/"
    type:     annotation
