school_classroom:
    resource: "@SchoolBundle/Controller/ClassroomController.php"
    type:     annotation

exercise_thumbnail:
    resource: "@ExerciseBundle/Controller/ThumbnailController.php"
    type:     annotation

school:
    resource: "@SchoolBundle/Controller/"
    type:     annotation
    prefix:   /

exercise:
    resource: "@ExerciseBundle/Controller/"
    type:     annotation
    prefix:   /

app:
    resource: "@AppBundle/Controller/"
    type:     annotation
