# To get started with security, check out the documentation:
# http://symfony.com/doc/current/security.html
security:

    # http://symfony.com/doc/current/security.html#b-configuring-how-users-are-loaded
    
    encoders:
        SchoolBundle\Entity\User: plaintext


    role_hierarchy:
        ROLE_TEACHER: [ROLE_USER]
        #ROLE_STUDENT: ROLE_USER
    providers:        
        userSchool: #nom arbitraire
            entity:
                class: SchoolBundle\Entity\User
                property: username

    firewalls:
        # disables authentication for assets and the profiler, adapt it according to your needs
        dev:
            pattern: ^/(_(profiler|wdt)|css|images|js)/
            security: false

       
        main:
            pattern: ^/
            anonymous: ~
            provider: userSchool
            form_login:
                login_path: login
                #check_path: login #login_check
            logout:
                path:   /logout
                target: /
            # activate different ways to authenticate

            # http_basic: ~
            # http://symfony.com/doc/current/security.html#a-configuring-how-your-users-will-authenticate

            # form_login: ~
            # http://symfony.com/doc/current/cookbook/security/form_login_setup.html
    access_control:
        - { path: ^/$, roles: IS_AUTHENTICATED_ANONYMOUSLY }
        - { path: ^/login, roles: IS_AUTHENTICATED_ANONYMOUSLY }
        - { path: ^/admin, roles: ROLE_TEACHER }
        - { path: ^/, role: IS_AUTHENTICATED_FULLY }
        
