# Learn more about services, parameters and containers at
# http://symfony.com/doc/current/service_container.html
parameters:


services:
#    service_name:
#        class: AppBundle\Directory\ClassName
#        arguments: ["@another_service_name", "plain_value", "%parameter_name%"]
    app.uploader:
        class: AppBundle\Service\FileUploader

    app.save_exercise_done:
        class: AppBundle\Service\SaveExerciseDone
        arguments: ["@doctrine.orm.entity_manager","@=service('security.token_storage').getToken().getUser()"]

    app.user_activity:
        class: AppBundle\Service\UserActivity
        arguments: ["@doctrine.orm.entity_manager","@=service('security.token_storage').getToken()"]

    app.user_activity.listener:
        class: AppBundle\EventListener\UserActivityListener
        arguments: ["@app.user_activity"]
        tags:
          - { name: kernel.event_listener, event: kernel.response, method: processUpdate }