# Learn more about services, parameters and containers at
# http://symfony.com/doc/current/service_container.html
parameters:


services:
#    service_name:
#        class: AppBundle\Directory\ClassName
#        arguments: ["@another_service_name", "plain_value", "%parameter_name%"]
    app.uploader:
        class: AppBundle\Service\FileUploader

    app.save_exercise_done:
        class: AppBundle\Service\SaveExerciseDone
        arguments: ["@doctrine.orm.entity_manager","@=service('security.token_storage').getToken().getUser()"]