parameters:
    thumbnails_directory: '%kernel.root_dir%/../web/exercise/thumbnails'
    thumbnails_directory_view: 'exercise/thumbnails'
    sound_directory: '%kernel.root_dir%/../web/exercise/records'

services:
#    exercise.example:
#        class: ExerciseBundle\Example
#        arguments: ["@service_id", "plain_value", "%parameter%"]
    exercise.get_exercise:
        class: ExerciseBundle\Service\GetExercise
        arguments: ["@doctrine.orm.entity_manager","@=service('security.token_storage').getToken().getUser()","@exercise.data","@exercise.stats_user"]

    exercise.mixing_thumbnails:
        class: ExerciseBundle\Service\MixingThumbnails
        arguments: ["@doctrine.orm.entity_manager","@exercise.data"]

    exercise.save_result:
        class: ExerciseBundle\Service\SaveResult
        arguments: ["@doctrine.orm.entity_manager","@app.save_exercise_done","@session"]

    exercise.stats_user:
        class: ExerciseBundle\Service\StatsUser
        arguments: ["@doctrine.orm.entity_manager"]

    exercise.data:
        class: ExerciseBundle\Service\ExerciseData
        arguments: ["@session"]

    exercise.last_done:
        class: ExerciseBundle\Service\LastDone
        arguments: ["@doctrine.orm.entity_manager"]