<?php

namespace ExerciceBundle\Repository;

use ExerciceBundle\Entity\Thumbnail;

/**
 * ThumbnailRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class ThumbnailRepository extends \Doctrine\ORM\EntityRepository
{
    public function getQui(){
        return $this->createQueryBuilder('Thumbnail')->where('Thumbnail.type=1');
    }
    public function getQuand(){
        return $this->createQueryBuilder('Thumbnail')->where('Thumbnail.type=2');
    }
    public function getOu(){
        return $this->createQueryBuilder('Thumbnail')->where('Thumbnail.type=3');
    }
}
